# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
locale: en-US
title: Scriptable Assets
title_separator: "|"
email: taro.tsukagoshi@gmail.com
description: Coding Kaizen into Our Workspace
# description: >- # this means to ignore newlines until "baseurl:"
#  Write an awesome description for your new site here. You can edit this
#  line in _config.yml. It will appear in your document head meta (for
#  Google search results) and in your feed.xml site description.
# twitter_username: username
github_username: ttsukagoshi
minimal_mistakes_skin: default
search: true

# Build settings
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
# paginate: 5 # amount of posts to show
# paginate_path: /page:num/
timezone: Asia/Tokyo
# https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
breadcrumbs: true  # disabled by default

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-redirect-from

# Analytics
analytics:
  provider: "google-gtag" # false (default), "google", "google-universal", "google-gtag", "custom"
  google:
    tracking_id: "G-Y4SZ8HKEJP"
    anonymize_ip: false # false (default)

author:
  name   : "Taro TSUKAGOSHI"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "An amateur engineer wiggling through his documents, searching continuously for ways to increase productivity and make a better workplace."
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://www.scriptable-assets.page/"
    # - label: "Twitter"
    #   icon: "fab fa-fw fa-twitter-square"
    #   url: "https://twitter.com/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/ttsukagoshi/"
    # - label: "Instagram"
    #   icon: "fab fa-fw fa-instagram"
    #   url: "https://instagram.com/"

footer:
  links:
    # - label: "Twitter"
    #   icon: "fab fa-fw fa-twitter-square"
    #   url: "https://twitter.com/"
    # - label: "Instagram"
    #   icon: "fab fa-fw fa-instagram"
    #   url: "https://instagram.com/"
    - label: "Terms & Conditions"
      url: "https://www.scriptable-assets.page/terms-and-conditions/"
    - label: "Privacy Policy"
      url: "https://www.scriptable-assets.page/privacy-policy/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/ttsukagoshi/"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: false

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
